name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Windows-Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Godot Headless Build
        # You may pin to the exact commit or the version.
        # uses: robpc/godot-export-action@2f0e808a7acdd7b4d60bc9eeb57379ee9a6b51ab
        uses: robpc/godot-export-action@v4.2-0
        with:
          # name of the export preset
          preset: windowsDesktop
          # export path for the executable
          export_path: ..\build\godot.exe          
