name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  exports:
    name: Export from Godot
    strategy:
      matrix:
        include:
          - preset: Web
            export_file: index.html
          - preset: WindowsDesktop
            export_file: godot-prac.exe
          - preset: Linux/X11
            export_file: godot-prac
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Export ${{ matrix.preset }} from Godot
        uses: robpc/godot-export-action@v4.2
        with:
          preset: ${{ matrix.preset }}
          export_path: build/${{ matrix.preset }}/${{ matrix.export_file }}
      - name: Bundle ${{ matrix.preset }} export
        uses: montudor/action-zip@v0.1.1
        with:
          args: >-
            zip --junk-paths --recurse-paths
            build/${{ env.package_prefix }}-v${{ env.version }}-${{ matrix.preset }}.zip
            build/${{ matrix.preset }}
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/*.zip
