name: Build Godot Project
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  build:
    name: Godot Export
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Godot Export
        # You may pin to the exact commit or the version.
        # uses: firebelley/godot-export@b0b8d3e350b7e4c376a865057961fa36e8ec3005
        uses: firebelley/godot-export@v5.2.1
        with:
          # The download url of the Linux Headless Godot executable.
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          # The url of the export templates corresponding to the Godot executable version.
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          # The path relative to the root of the git repository that contains the "project.godot" file.
          relative_project_path: ./
          archive_output: true

      # This release action has worked well for me. However, you can most likely use any release action of your choosing.
      # https://github.com/ncipollo/release-action
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: false
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
            
